controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

search_students:
    path: /search
    controller: App\Controller\StudentController::search
